version: '3.8'
services:
  postgres-hotel-reservation:
    image: postgres:latest
    container_name: psql-hotel-reservation
    environment:
      POSTGRES_DB: hotel-reservation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-hotel-reservation:/data/postgres
    expose:
      - "5430"
    ports:
      - "5430:5430"
    command: -p 5430
    restart: always

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-hotel-reservation:
