version: '3.8'
services:
  postgres-hotel-reservation:
    image: postgres:latest
    container_name: psql-hotel-reservation
    environment:
      POSTGRES_DB: hotel-reservation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-hotel-reservation:/data/postgres
    expose:
      - "5430"
    ports:
      - "5430:5430"
    command: -p 5430
    restart: always

volumes:
  postgres-hotel-reservation:
